version: "3.9"
services:
  app:
    build:
      context: target
      dockerfile: ../Dockerfile
    networks:
      - usernetworkapplication
    ports:
      - "8077:8077"
    depends_on:
      - databasepostgresql

  databasepostgresql:
    image: postgres:13.1
    networks:
      - usernetworkapplication
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=user
    volumes:
      - ./databaseData:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

networks:
  usernetworkapplication:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1