spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false